
CREATE OR REPLACE DIRECTORY data_dir AS '/home/vagrant/vagrant-ubuntu-oracle-xe/data';

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE JMETER';
EXCEPTION
  WHEN OTHERS THEN
    IF sqlcode != -0942 THEN RAISE; END IF;
END;
/

CREATE TABLE "JMETER" 
   (	"TS" NUMBER(13,0), 
	"ELAPSED" NUMBER(8,0), 
	"LABEL" VARCHAR2(200 BYTE), 
	"RC" NUMBER(3,0), 
	"RESPONSEMSG" VARCHAR2(200 BYTE), 
	"THREADNAME" VARCHAR2(200 BYTE), 
	"DATATYPE" VARCHAR2(50 BYTE), 
	"SUCCESS" VARCHAR2(10 BYTE), 
	"BYTES" VARCHAR2(20 BYTE), 
	"GRPTHREADS" VARCHAR2(10 BYTE), 
	"ALLTHREADS" VARCHAR2(10 BYTE), 
	"LATENCY" VARCHAR2(10 BYTE), 
	"SAMPLECOUNT" VARCHAR2(3 BYTE), 
	"ERRORCOUNT" VARCHAR2(3 BYTE), 
	"HOSTNAME" VARCHAR2(100 BYTE), 
	"TESTID" VARCHAR2(50 BYTE)
   ) ORGANIZATION EXTERNAL
	( TYPE ORACLE_LOADER
	DEFAULT DIRECTORY data_dir
	ACCESS PARAMETERS
	(FIELDS TERMINATED by ';' )
LOCATION ('jmeter.log')
)
REJECT LIMIT UNLIMITED;

quit;
